# Generated by Django 3.0.5 on 2020-04-19 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d/')),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 44, 7, 959637), verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
